version: '3'
services:
  database:
    image: mysql/mysql-server:latest
    container_name: mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
        - ./mysql-init:/var/lib/mysql:rw
        - ./mysql-init/locations_schema.sql:/docker-entrypoint-initdb.d/locations_schema.sql:ro
  phpmyadmin:
   image: phpmyadmin/phpmyadmin:latest
   links:
     - database
   ports:
     - 8181:80
   environment:
     MYSQL_USERNAME: root
     MYSQL_ROOT_PASSWORD: abc1232018
     PMA_HOST: database
     PMA_PORT: 3306
