version: '2'

services:
nginx: 
  build: nginx
  restart: always
  ports:
  - 8080:80
  volumes_from:
  - wordpress

wordpress:
  image: wordpress:php7.1-fpm-alpine
  environment:
  WORDPRESS_DB_HOST: mysql
  WORDPRESS_DB_PASSWORD: example

mysql:
  image: mariadb
  environment:
  MYSQL_ROOT_PASSWORD: example
  volumes:
  - ./demo-db:/var/lib/mysql
